export type FiscalLibraryOption = {
  code: string;
  label: string;
  description?: string;
};

export type FiscalNcmPreset = {
  id: string;
  segment: string;
  label: string;
  ncm: string;
  officialDescription: string;
  defaultUnit: string;
  keywords: string[];
  usageNote: string;
  validationLevel: "high" | "medium";
  source: string;
};

export type FiscalCestOption = FiscalLibraryOption & {
  ncmPrefixes: string[];
  packagingNote?: string;
};

export const fiscalNcmPresets: FiscalNcmPreset[] = [
  {
    id: "prepared-meals-generic",
    segment: "Refeições e lanches",
    label: "Refeições preparadas — candidato genérico",
    ncm: "21069090",
    officialDescription: "Outras preparações alimentícias",
    defaultUnit: "UN",
    keywords: ["refeição", "marmita", "prato", "pizza", "hambúrguer", "lanche", "combo"],
    usageNote:
      "Candidato amplo. A composição real do produto pode exigir outro NCM; confirme com XML anterior ou contador.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 21.06",
  },
  {
    id: "prepared-soup",
    segment: "Refeições e lanches",
    label: "Caldos e sopas preparados",
    ncm: "21041029",
    officialDescription: "Outros caldos e sopas preparados",
    defaultUnit: "UN",
    keywords: ["caldo", "sopa", "canja"],
    usageNote: "Confirme se a forma de apresentação se enquadra nesta abertura.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 21.04",
  },
  {
    id: "stuffed-pasta",
    segment: "Massas",
    label: "Massas recheadas",
    ncm: "19022000",
    officialDescription: "Massas alimentícias recheadas, mesmo cozidas ou preparadas de outro modo",
    defaultUnit: "UN",
    keywords: ["lasanha", "ravioli", "raviolone", "canelone", "massa recheada"],
    usageNote: "A classificação depende da composição e apresentação da massa.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 19.02",
  },
  {
    id: "other-pasta",
    segment: "Massas",
    label: "Outras massas alimentícias",
    ncm: "19023000",
    officialDescription: "Outras massas alimentícias",
    defaultUnit: "UN",
    keywords: ["macarrão", "espaguete", "nhoque", "massa"],
    usageNote: "Use somente quando a mercadoria corresponder à descrição oficial.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 19.02",
  },
  {
    id: "bakery-pastry-other",
    segment: "Padaria, pizzas e confeitaria",
    label: "Outros produtos de padaria e pastelaria",
    ncm: "19059090",
    officialDescription: "Outros produtos de padaria, pastelaria ou da indústria de bolachas e biscoitos",
    defaultUnit: "UN",
    keywords: ["pizza", "salgado", "bolo", "torta", "pão", "pastel", "croissant"],
    usageNote:
      "Muito amplo. Pizza, bolo, salgado ou outro produto pode exigir análise específica de ingredientes e apresentação.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 19.05",
  },
  {
    id: "bread-loaf",
    segment: "Padaria, pizzas e confeitaria",
    label: "Pão de forma",
    ncm: "19059010",
    officialDescription: "Pão de forma",
    defaultUnit: "UN",
    keywords: ["pão de forma"],
    usageNote: "Aplicável ao produto vendido como pão de forma.",
    validationLevel: "medium",
    source: "Tabela NCM oficial — posição 19.05",
  },
  {
    id: "biscuits",
    segment: "Padaria, pizzas e confeitaria",
    label: "Bolachas e biscoitos",
    ncm: "19059020",
    officialDescription: "Bolachas e biscoitos",
    defaultUnit: "UN",
    keywords: ["biscoito", "bolacha"],
    usageNote: "Confirme embalagem e características do produto vendido.",
    validationLevel: "medium",
    source: "Tabela NCM oficial — posição 19.05",
  },
  {
    id: "waffles-wafers",
    segment: "Padaria, pizzas e confeitaria",
    label: "Waffles e wafers",
    ncm: "19053200",
    officialDescription: "Waffles e wafers",
    defaultUnit: "UN",
    keywords: ["waffle", "wafer"],
    usageNote: "Confirme se o produto corresponde à descrição oficial.",
    validationLevel: "medium",
    source: "Tabela NCM oficial — posição 19.05",
  },
  {
    id: "sausages",
    segment: "Carnes e lanches",
    label: "Enchidos e produtos semelhantes",
    ncm: "16010000",
    officialDescription: "Enchidos e produtos semelhantes, de carne, miudezas, sangue ou de insetos",
    defaultUnit: "UN",
    keywords: ["salsicha", "linguiça", "calabresa", "hot dog", "cachorro-quente"],
    usageNote:
      "Normalmente descreve a mercadoria cárnea, não necessariamente o sanduíche completo servido ao consumidor.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 16.01",
  },
  {
    id: "beef-preparation",
    segment: "Carnes e lanches",
    label: "Preparações de carne bovina",
    ncm: "16025000",
    officialDescription: "Outras preparações e conservas de carne da espécie bovina",
    defaultUnit: "UN",
    keywords: ["hambúrguer bovino", "carne preparada", "almôndega"],
    usageNote:
      "Pode servir para preparação cárnea; não aplique automaticamente ao sanduíche completo sem validação.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 16.02",
  },
  {
    id: "chicken-preparation",
    segment: "Carnes e lanches",
    label: "Outras preparações de frango",
    ncm: "16023290",
    officialDescription: "Outras preparações de aves da espécie Gallus domesticus",
    defaultUnit: "UN",
    keywords: ["frango preparado", "nuggets", "hambúrguer de frango"],
    usageNote: "Confirme percentual de carne, cozimento e apresentação.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 16.02",
  },
  {
    id: "fish-preparation",
    segment: "Peixes e comida oriental",
    label: "Outras preparações de peixes",
    ncm: "16042090",
    officialDescription: "Outras preparações e conservas de peixes",
    defaultUnit: "UN",
    keywords: ["peixe preparado", "sushi", "temaki", "sashimi", "poke"],
    usageNote:
      "Sushi, temaki e pratos compostos podem não se enquadrar apenas pela presença de peixe. Validação obrigatória.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 16.04",
  },
  {
    id: "frozen-potatoes",
    segment: "Porções e acompanhamentos",
    label: "Batatas preparadas ou conservadas, congeladas",
    ncm: "20041000",
    officialDescription: "Batatas preparadas ou conservadas, congeladas",
    defaultUnit: "UN",
    keywords: ["batata congelada", "batata frita congelada"],
    usageNote: "Indicado para mercadoria congelada; não presuma para batata fresca preparada na loja.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 20.04",
  },
  {
    id: "potatoes-not-frozen",
    segment: "Porções e acompanhamentos",
    label: "Batatas preparadas ou conservadas, não congeladas",
    ncm: "20052000",
    officialDescription: "Batatas preparadas ou conservadas, não congeladas",
    defaultUnit: "UN",
    keywords: ["batata", "chips", "batata não congelada"],
    usageNote: "Confirme forma de preparo e conservação.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 20.05",
  },
  {
    id: "acai-puree",
    segment: "Açaí, frutas e sobremesas",
    label: "Purê de açaí",
    ncm: "20079921",
    officialDescription: "Purês de açaí (Euterpe oleracea)",
    defaultUnit: "UN",
    keywords: ["açaí", "purê de açaí", "polpa de açaí"],
    usageNote:
      "Açaí pronto com xaropes, frutas, leite ou outros adicionais pode exigir classificação diferente.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 20.07",
  },
  {
    id: "ice-cream-small-pack",
    segment: "Açaí, frutas e sobremesas",
    label: "Sorvete em embalagem imediata até 2 kg",
    ncm: "21050010",
    officialDescription: "Sorvetes em embalagens imediatas de conteúdo inferior ou igual a 2 kg",
    defaultUnit: "UN",
    keywords: ["sorvete", "picolé", "gelato", "casquinha"],
    usageNote: "Confirme embalagem e se o item corresponde a sorvete da posição 21.05.",
    validationLevel: "medium",
    source: "Tabela NCM oficial — posição 21.05",
  },
  {
    id: "ice-cream-other",
    segment: "Açaí, frutas e sobremesas",
    label: "Outros sorvetes",
    ncm: "21050090",
    officialDescription: "Outros sorvetes",
    defaultUnit: "UN",
    keywords: ["sorvete", "gelato", "sobremesa gelada"],
    usageNote: "Use quando não se enquadrar na abertura de embalagem até 2 kg.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 21.05",
  },
  {
    id: "confectionery-no-cocoa",
    segment: "Doces e sobremesas",
    label: "Outros produtos de confeitaria sem cacau",
    ncm: "17049090",
    officialDescription: "Outros produtos de confeitaria sem cacau",
    defaultUnit: "UN",
    keywords: ["doce", "bala", "confeito", "sobremesa sem cacau"],
    usageNote: "Confirme ingredientes e presença de cacau.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 17.04",
  },
  {
    id: "chocolate-other",
    segment: "Doces e sobremesas",
    label: "Outras preparações com cacau",
    ncm: "18069000",
    officialDescription: "Outros chocolates e preparações alimentícias que contenham cacau",
    defaultUnit: "UN",
    keywords: ["chocolate", "brigadeiro", "sobremesa com cacau"],
    usageNote: "Bolos, sorvetes e sobremesas compostas podem ter enquadramento próprio.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 18.06",
  },
  {
    id: "yogurt",
    segment: "Lácteos e café da manhã",
    label: "Iogurte",
    ncm: "04032000",
    officialDescription: "Iogurte",
    defaultUnit: "UN",
    keywords: ["iogurte"],
    usageNote: "Confirme se é produto industrializado vendido como iogurte.",
    validationLevel: "medium",
    source: "Tabela NCM oficial — posição 04.03",
  },
  {
    id: "mozzarella",
    segment: "Lácteos e café da manhã",
    label: "Mozarela",
    ncm: "04061010",
    officialDescription: "Queijo fresco — mozarela",
    defaultUnit: "KG",
    keywords: ["mozarela", "muçarela", "queijo"],
    usageNote: "Use para a mercadoria queijo vendida separadamente, não para pizza pronta.",
    validationLevel: "medium",
    source: "Tabela NCM oficial — posição 04.06",
  },
  {
    id: "roasted-coffee",
    segment: "Cafeterias e bebidas quentes",
    label: "Café torrado não descafeinado",
    ncm: "09012100",
    officialDescription: "Café torrado, não descafeinado",
    defaultUnit: "UN",
    keywords: ["café torrado", "café em grão", "café moído"],
    usageNote: "Refere-se ao café como mercadoria; bebida preparada e servida pode exigir análise diferente.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 09.01",
  },
  {
    id: "mineral-water",
    segment: "Bebidas",
    label: "Água mineral ou gaseificada",
    ncm: "22011000",
    officialDescription: "Águas minerais e águas gaseificadas",
    defaultUnit: "UN",
    keywords: ["água mineral", "água com gás"],
    usageNote: "O CEST varia conforme embalagem e capacidade.",
    validationLevel: "medium",
    source: "Tabela NCM oficial — posição 22.01",
  },
  {
    id: "other-water",
    segment: "Bebidas",
    label: "Outras águas",
    ncm: "22019000",
    officialDescription: "Outras águas não adicionadas de açúcar nem aromatizadas",
    defaultUnit: "UN",
    keywords: ["água", "água potável"],
    usageNote: "Confirme a descrição, composição e embalagem.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 22.01",
  },
  {
    id: "soft-drink",
    segment: "Bebidas",
    label: "Refrigerantes e águas aromatizadas com açúcar",
    ncm: "22021000",
    officialDescription: "Águas adicionadas de açúcar, edulcorantes ou aromatizadas",
    defaultUnit: "UN",
    keywords: ["refrigerante", "coca", "guaraná", "soda", "água aromatizada"],
    usageNote: "O CEST depende do tipo de bebida e da embalagem: PET, lata, vidro ou outras.",
    validationLevel: "medium",
    source: "Tabela NCM oficial — posição 22.02",
  },
  {
    id: "other-non-alcoholic-beverage",
    segment: "Bebidas",
    label: "Outras bebidas não alcoólicas",
    ncm: "22029900",
    officialDescription: "Outras bebidas não alcoólicas",
    defaultUnit: "UN",
    keywords: ["energético", "isotônico", "néctar", "bebida láctea", "chá pronto"],
    usageNote: "A descrição e o CEST variam conforme a bebida. Confirme antes de usar.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 22.02",
  },
  {
    id: "fruit-juice-mixture",
    segment: "Bebidas",
    label: "Misturas de sucos",
    ncm: "20099000",
    officialDescription: "Misturas de sucos de fruta ou de produtos hortícolas",
    defaultUnit: "UN",
    keywords: ["suco misto", "mix de sucos", "suco de frutas"],
    usageNote: "Sucos de uma única fruta possuem códigos específicos. O CEST pode ser 17.010.00.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 20.09",
  },
  {
    id: "coconut-water",
    segment: "Bebidas",
    label: "Água de coco",
    ncm: "20098921",
    officialDescription: "Água de coco com valor Brix não superior a 7,4",
    defaultUnit: "UN",
    keywords: ["água de coco"],
    usageNote: "O código varia com o valor Brix. Confirme o rótulo ou XML do fornecedor.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 20.09",
  },
  {
    id: "beer",
    segment: "Bebidas alcoólicas",
    label: "Cerveja de malte",
    ncm: "22030000",
    officialDescription: "Cervejas de malte",
    defaultUnit: "UN",
    keywords: ["cerveja", "long neck", "latão", "chope"],
    usageNote: "O CEST muda conforme garrafa, lata, barril, PET ou chope.",
    validationLevel: "medium",
    source: "Tabela NCM oficial — posição 22.03",
  },
  {
    id: "non-alcoholic-beer",
    segment: "Bebidas alcoólicas",
    label: "Cerveja sem álcool",
    ncm: "22029100",
    officialDescription: "Cerveja sem álcool",
    defaultUnit: "UN",
    keywords: ["cerveja sem álcool", "cerveja zero"],
    usageNote: "O CEST varia conforme a embalagem.",
    validationLevel: "medium",
    source: "Tabela NCM oficial — posição 22.02",
  },
  {
    id: "wine-small-container",
    segment: "Bebidas alcoólicas",
    label: "Vinhos em recipientes de até 2 litros",
    ncm: "22042100",
    officialDescription: "Outros vinhos em recipientes de capacidade não superior a 2 litros",
    defaultUnit: "UN",
    keywords: ["vinho", "vinho tinto", "vinho branco", "vinho rosé"],
    usageNote: "Espumantes e recipientes maiores possuem outras classificações.",
    validationLevel: "high",
    source: "Tabela NCM oficial — posição 22.04",
  },
];

export const fiscalCfopOptions: FiscalLibraryOption[] = [
  {
    code: "5101",
    label: "Venda de produção do estabelecimento",
    description: "Candidato comum para item produzido pelo próprio estabelecimento em operação interna.",
  },
  {
    code: "5102",
    label: "Venda de mercadoria adquirida ou recebida de terceiros",
    description: "Candidato comum para revenda sem substituição tributária em operação interna.",
  },
  {
    code: "5405",
    label: "Venda de mercadoria de terceiros sujeita à ST — contribuinte substituído",
    description: "Candidato comum para revenda quando o ICMS-ST já foi retido anteriormente.",
  },
  {
    code: "6101",
    label: "Venda interestadual de produção do estabelecimento",
    description: "Use somente quando a operação realmente for interestadual.",
  },
  {
    code: "6102",
    label: "Venda interestadual de mercadoria adquirida de terceiros",
    description: "Use somente quando a operação realmente for interestadual.",
  },
];

export const fiscalOriginOptions: FiscalLibraryOption[] = [
  { code: "0", label: "Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8" },
  { code: "1", label: "Estrangeira — importação direta, exceto código 6" },
  { code: "2", label: "Estrangeira — adquirida no mercado interno, exceto código 7" },
  { code: "3", label: "Nacional com conteúdo de importação superior a 40% e até 70%" },
  { code: "4", label: "Nacional produzida conforme processos produtivos básicos" },
  { code: "5", label: "Nacional com conteúdo de importação inferior ou igual a 40%" },
  { code: "6", label: "Estrangeira — importação direta, sem similar nacional" },
  { code: "7", label: "Estrangeira — adquirida no mercado interno, sem similar nacional" },
  { code: "8", label: "Nacional com conteúdo de importação superior a 70%" },
];

export const fiscalCsosnOptions: FiscalLibraryOption[] = [
  { code: "101", label: "Tributada pelo Simples Nacional com permissão de crédito" },
  { code: "102", label: "Tributada pelo Simples Nacional sem permissão de crédito" },
  { code: "103", label: "Isenção do ICMS no Simples Nacional para faixa de receita" },
  { code: "201", label: "Tributada pelo Simples com crédito e cobrança por ST" },
  { code: "202", label: "Tributada pelo Simples sem crédito e com cobrança por ST" },
  { code: "203", label: "Isenção do ICMS no Simples e cobrança por ST" },
  { code: "300", label: "Imune" },
  { code: "400", label: "Não tributada pelo Simples Nacional" },
  { code: "500", label: "ICMS cobrado anteriormente por ST ou antecipação" },
  { code: "900", label: "Outros" },
];

export const fiscalCstIcmsOptions: FiscalLibraryOption[] = [
  { code: "00", label: "Tributada integralmente" },
  { code: "10", label: "Tributada e com cobrança do ICMS por ST" },
  { code: "20", label: "Com redução de base de cálculo" },
  { code: "30", label: "Isenta ou não tributada e com cobrança do ICMS por ST" },
  { code: "40", label: "Isenta" },
  { code: "41", label: "Não tributada" },
  { code: "50", label: "Suspensão" },
  { code: "51", label: "Diferimento" },
  { code: "60", label: "ICMS cobrado anteriormente por ST" },
  { code: "70", label: "Redução de base e cobrança do ICMS por ST" },
  { code: "90", label: "Outras" },
];

export const fiscalPisCofinsOptions: FiscalLibraryOption[] = [
  { code: "01", label: "Operação tributável com alíquota básica" },
  { code: "02", label: "Operação tributável com alíquota diferenciada" },
  { code: "03", label: "Operação tributável por unidade de medida de produto" },
  { code: "04", label: "Operação tributável monofásica — revenda a alíquota zero" },
  { code: "05", label: "Operação tributável por substituição tributária" },
  { code: "06", label: "Operação tributável a alíquota zero" },
  { code: "07", label: "Operação isenta da contribuição" },
  { code: "08", label: "Operação sem incidência da contribuição" },
  { code: "09", label: "Operação com suspensão da contribuição" },
  { code: "49", label: "Outras operações de saída" },
  { code: "99", label: "Outras operações" },
];

export const fiscalUnitOptions: FiscalLibraryOption[] = [
  { code: "UN", label: "Unidade" },
  { code: "KG", label: "Quilograma" },
  { code: "G", label: "Grama" },
  { code: "L", label: "Litro" },
  { code: "ML", label: "Mililitro" },
  { code: "CX", label: "Caixa" },
  { code: "PCT", label: "Pacote" },
  { code: "FD", label: "Fardo" },
  { code: "BDJ", label: "Bandeja" },
  { code: "POR", label: "Porção — confirmar aceitação no provedor fiscal" },
];

export const fiscalCestOptions: FiscalCestOption[] = [
  {
    code: "2300100",
    label: "Sorvetes de qualquer espécie",
    description: "CEST 23.001.00",
    ncmPrefixes: ["210500"],
  },
  {
    code: "1701000",
    label: "Sucos de frutas ou produtos hortícolas; mistura de sucos",
    description: "CEST 17.010.00",
    ncmPrefixes: ["2009"],
  },
  {
    code: "1701100",
    label: "Água de coco",
    description: "CEST 17.011.00",
    ncmPrefixes: ["2009892"],
  },
  {
    code: "0301000",
    label: "Refrigerante em vidro descartável",
    description: "CEST 03.010.00",
    ncmPrefixes: ["22021000", "22029900"],
    packagingNote: "Vidro descartável",
  },
  {
    code: "0301001",
    label: "Refrigerante em embalagem PET",
    description: "CEST 03.010.01",
    ncmPrefixes: ["22021000", "22029900"],
    packagingNote: "PET",
  },
  {
    code: "0301002",
    label: "Refrigerante em lata",
    description: "CEST 03.010.02",
    ncmPrefixes: ["22021000", "22029900"],
    packagingNote: "Lata",
  },
  {
    code: "0301100",
    label: "Demais refrigerantes",
    description: "CEST 03.011.00",
    ncmPrefixes: ["22021000", "22029900"],
    packagingNote: "Outras embalagens",
  },
  {
    code: "0302101",
    label: "Cerveja em garrafa de vidro descartável",
    description: "CEST 03.021.01",
    ncmPrefixes: ["22030000"],
    packagingNote: "Vidro descartável",
  },
  {
    code: "0302103",
    label: "Cerveja em lata",
    description: "CEST 03.021.03",
    ncmPrefixes: ["22030000"],
    packagingNote: "Lata",
  },
  {
    code: "0302104",
    label: "Cerveja em barril",
    description: "CEST 03.021.04",
    ncmPrefixes: ["22030000"],
    packagingNote: "Barril",
  },
  {
    code: "0302105",
    label: "Cerveja em embalagem PET",
    description: "CEST 03.021.05",
    ncmPrefixes: ["22030000"],
    packagingNote: "PET",
  },
  {
    code: "0302106",
    label: "Cerveja em outras embalagens",
    description: "CEST 03.021.06",
    ncmPrefixes: ["22030000"],
    packagingNote: "Outras embalagens",
  },
  {
    code: "0302300",
    label: "Chope",
    description: "CEST 03.023.00",
    ncmPrefixes: ["22030000"],
    packagingNote: "Chope",
  },
];

export function getFiscalCodeLibrary(taxRegime: string | null) {
  const usesCsosn = taxRegime === "simples_nacional" || taxRegime === "simples_excesso";
  return {
    version: "2026-06-initial",
    warning:
      "A biblioteca oferece candidatos e listas de apoio. Nenhum código substitui a validação do contador, dos XMLs anteriores e da legislação estadual.",
    ncmPresets: fiscalNcmPresets,
    cestOptions: fiscalCestOptions,
    cfopOptions: fiscalCfopOptions,
    originOptions: fiscalOriginOptions,
    icmsOptions: usesCsosn ? fiscalCsosnOptions : fiscalCstIcmsOptions,
    icmsLabel: usesCsosn ? "CSOSN" : "CST ICMS",
    pisOptions: fiscalPisCofinsOptions,
    cofinsOptions: fiscalPisCofinsOptions,
    unitOptions: fiscalUnitOptions,
  };
}
