import { Router, type IRouter } from "express";
import healthRouter from "./health";
import tablesRouter from "./tables";
import customersRouter from "./customers";
import menuRouter from "./menu";
import ordersRouter from "./orders";
import paymentsRouter from "./payments";
import kitchenRouter from "./kitchen";
import dashboardRouter from "./dashboard";
import cashOpenRouter from "./cash-open";
import cashRouter from "./cash";
import deliveryRouter from "./delivery";
import couriersRouter from "./couriers";
import settingsRouter from "./settings";
import openRouteServiceSettingsRouter from "./openrouteservice-settings";
import alertsRouter from "./alerts";
import integrationsRouter from "./integrations";
import deliveryDistanceRouter from "./delivery-distance";
import devRouter from "./dev";
import adminRouter from "./admin";
import authRouter from "./auth";
import platformUsersRouter from "./platform-users";
import storeInfoRouter from "./platform-store-details";
import platformRouter from "./platform";
import onboardingRouter from "./onboarding";
import billingRouter from "./billing";
import caktoRouter from "./cakto";
import teamRouter from "./team";
import fiscalAccessStatusRouter from "./fiscal-access-status";
import fiscalAccessRouter from "./fiscal-access";
import fiscalCatalogRouter from "./fiscal-catalog";
import fiscalCodeLibraryRouter from "./fiscal-code-library";
import fiscalGuideRouter from "./fiscal-guide";
import fiscalFocusRouter from "./fiscal-focus";
import fiscalNfceRouter from "./fiscal-nfce";
import { attachCurrentActor, rbacRouteGuard } from "../middleware/rbac";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(platformUsersRouter);
router.use(storeInfoRouter);
router.use(platformRouter);
router.use(onboardingRouter);
router.use(billingRouter);
router.use(caktoRouter);
router.use(fiscalAccessStatusRouter);

router.use(attachCurrentActor);
router.use(rbacRouteGuard);

router.use(tablesRouter);
router.use(customersRouter);
router.use(menuRouter);
router.use(ordersRouter);
router.use(paymentsRouter);
router.use(kitchenRouter);
router.use(dashboardRouter);
router.use(cashOpenRouter);
router.use(cashRouter);
router.use(deliveryRouter);
router.use(couriersRouter);
router.use(settingsRouter);
router.use(openRouteServiceSettingsRouter);
router.use(teamRouter);
router.use(fiscalAccessRouter);
router.use(fiscalCatalogRouter);
router.use(fiscalCodeLibraryRouter);
router.use(fiscalGuideRouter);
router.use(fiscalFocusRouter);
router.use(fiscalNfceRouter);
router.use(alertsRouter);
router.use(integrationsRouter);
router.use(deliveryDistanceRouter);
router.use(devRouter);
router.use(adminRouter);

export default router;
