import { eq, sql } from "drizzle-orm";
import { db, fiscalDocumentsTable, storeFiscalSettingsTable } from "@workspace/db";
import { FocusNfeClient } from "./client";
import { getFocusCompanySummary, resolveStoreFocusCredentials } from "./company-service";
import { FocusNfeError } from "./errors";
import { audit, findNfceDocument, reserveHomologationNfce, toSafeNfceDocument } from "./nfce-repository";
import { NfceServiceError, type FocusNfceResponse, type NfceLocalStatus } from "./nfce-types";

function getStr(o:Record<string,unknown>, keys:string[]){ for (const k of keys) if (typeof o[k] === "string" && o[k]) return o[k] as string; return null; }
function normalize(data: FocusNfceResponse){ const status=getStr(data,["status"]); const statusSefaz=getStr(data,["status_sefaz"]); const rejection=getStr(data,["codigo_rejeicao","codigo_status","status_sefaz"]); const msg=getStr(data,["mensagem_sefaz","mensagem","motivo","mensagem_rejeicao"]); const map:Record<string,NfceLocalStatus>={ autorizado:"authorized", cancelado:"cancelled", processamento:"processing", processando:"processing", em_processamento:"processing", erro_autorizacao:"rejected", denegado:"rejected", rejeitado:"rejected", erro:"error" }; const local = status ? (map[status] ?? "processing") : "processing"; const authorized = status === "autorizado" && statusSefaz === "100"; const rejected = ["erro_autorizacao","denegado","rejeitado"].includes(status ?? ""); return { status: authorized?"authorized":local, providerStatus:status, accessKey:getStr(data,["chave_nfe","chave","chave_acesso"]), protocol:getStr(data,["protocolo","numero_protocolo"]), xmlUrl:getStr(data,["caminho_xml_nota_fiscal"]), danfceUrl:getStr(data,["caminho_danfe","caminho_danfce"]), rejectionCode: rejected?rejection:null, rejectionMessage: rejected?msg:null } as const; }
async function assertSetupReady(storeId:number){ const summary=await getFocusCompanySummary(storeId); if(!summary.readyForHomologationTest) throw new NfceServiceError("FISCAL_SETUP_NOT_READY","Configuração fiscal não está pronta para homologação."); }
async function applyResult(storeId:number,userId:number,docId:number,data:FocusNfceResponse, checked=false){ const n=normalize(data); const now=new Date(); const [updated]=await db.transaction(async(tx:any)=>{ const [d]=await tx.update(fiscalDocumentsTable).set({ status:n.status, providerStatus:n.providerStatus, accessKey:n.accessKey, protocol:n.protocol, xmlUrl:n.xmlUrl, danfceUrl:n.danfceUrl, rejectionCode:n.rejectionCode, rejectionMessage:n.rejectionMessage, lastCheckedAt:checked?now:undefined, authorizedAt:n.status==="authorized"?now:undefined }).where(eq(fiscalDocumentsTable.id,docId)).returning(); if(n.status==="authorized"){ await tx.update(storeFiscalSettingsTable).set({ certificateStatus:"valid", setupStatus:"homologation" }).where(eq(storeFiscalSettingsTable.storeId, storeId)); } return [d]; }); if(n.status==="authorized"){ await audit(storeId,userId,"nfce_homologation_authorized",docId,{ fiscalDocumentId:docId, status:n.status, accessKey:n.accessKey, protocol:n.protocol }); await audit(storeId,userId,"fiscal_certificate_confirmed_by_authorized_nfce",docId,{ fiscalDocumentId:docId, status:n.status }); await audit(storeId,userId,"fiscal_homologation_confirmed",docId,{ fiscalDocumentId:docId, status:n.status }); } else if(n.status==="rejected") await audit(storeId,userId,"nfce_homologation_rejected",docId,{ fiscalDocumentId:docId, status:n.status, rejectionCode:n.rejectionCode }); else await audit(storeId,userId,"nfce_homologation_processing",docId,{ fiscalDocumentId:docId, status:n.status }); return toSafeNfceDocument(updated); }
export class NfceService { constructor(private client = new FocusNfeClient()){}
  async issueHomologation(storeId:number, orderId:number, userId:number){ await assertSetupReady(storeId); const doc=await reserveHomologationNfce(storeId,orderId,userId); if(doc.status==="authorized") throw new NfceServiceError("NFCE_ALREADY_AUTHORIZED","NFC-e já autorizada."); if(doc.status==="rejected") throw new NfceServiceError("NFCE_REJECTED","NFC-e rejeitada. Use a atualização de status antes de corrigir em um fluxo futuro."); if(doc.status==="sync_pending") throw new NfceServiceError("FISCAL_DOCUMENT_SYNC_PENDING","Documento fiscal pendente de sincronização com a Focus.",202); if(["submitting","processing"].includes(doc.status)) throw new NfceServiceError("NFCE_PROCESSING","NFC-e em processamento."); await db.update(fiscalDocumentsTable).set({ status:"submitting", attemptCount: sql`${fiscalDocumentsTable.attemptCount} + 1`, lastAttemptAt:new Date() }).where(eq(fiscalDocumentsTable.id,doc.id)); await audit(storeId,userId,"nfce_homologation_submitted",doc.id,{ fiscalDocumentId:doc.id, status:"submitting", series:doc.series, number:doc.number, providerReference:doc.providerReference }); const context=await resolveStoreFocusCredentials({ storeId, environment:"homologation" }); try { const result=await this.client.request<FocusNfceResponse>(context,{ method:"POST", path:`/v2/nfce?ref=${encodeURIComponent(doc.providerReference)}`, idempotencyReference:doc.providerReference, body:doc.payloadSnapshot }); return applyResult(storeId,userId,doc.id,result.data); } catch(e){ if(e instanceof FocusNfeError && (e.kind==="timeout" || e.kind==="communication" || e.kind==="temporary_unavailable")){ try { const r=await this.client.request<FocusNfceResponse>(context,{ method:"GET", path:`/v2/nfce/${encodeURIComponent(doc.providerReference)}` }); return applyResult(storeId,userId,doc.id,r.data,true); } catch { await db.update(fiscalDocumentsTable).set({ status:"sync_pending", lastCheckedAt:new Date() }).where(eq(fiscalDocumentsTable.id,doc.id)); await audit(storeId,userId,"nfce_homologation_sync_pending",doc.id,{ fiscalDocumentId:doc.id, status:"sync_pending", providerReference:doc.providerReference }); throw new NfceServiceError("FISCAL_DOCUMENT_SYNC_PENDING","Não foi possível confirmar a situação da NFC-e na Focus.",202); } } if(e instanceof FocusNfeError && e.kind==="timeout") throw new NfceServiceError("FOCUS_NFCE_TIMEOUT","Tempo esgotado ao comunicar com a Focus.",504); if(e instanceof FocusNfeError && e.kind==="validation") throw new NfceServiceError("FOCUS_NFCE_VALIDATION_ERROR","Focus rejeitou a validação da NFC-e.",422); throw new NfceServiceError("FOCUS_NFCE_UNAVAILABLE","Focus NFe indisponível.",503); } }
  async getLocal(storeId:number,orderId:number){ const d=await findNfceDocument(storeId,orderId); if(!d) throw new NfceServiceError("ORDER_NOT_FOUND","Documento fiscal não encontrado.",404); return toSafeNfceDocument(d); }
  async refresh(storeId:number,orderId:number,userId:number){ await assertSetupReady(storeId); const doc=await findNfceDocument(storeId,orderId); if(!doc) throw new NfceServiceError("ORDER_NOT_FOUND","Documento fiscal não encontrado.",404); const context=await resolveStoreFocusCredentials({ storeId, environment:"homologation" }); try { const r=await this.client.request<FocusNfceResponse>(context,{ method:"GET", path:`/v2/nfce/${encodeURIComponent(doc.providerReference)}` }); return applyResult(storeId,userId,doc.id,r.data,true); } catch { await db.update(fiscalDocumentsTable).set({ status:"sync_pending", lastCheckedAt:new Date() }).where(eq(fiscalDocumentsTable.id,doc.id)); throw new NfceServiceError("FISCAL_DOCUMENT_SYNC_PENDING","Consulta pendente de sincronização.",202); } }
}
export function sendNfceError(res:any,error:unknown){ if(error instanceof NfceServiceError) return res.status(error.status).json({ code:error.code, error:error.message }); return res.status(500).json({ code:"FOCUS_NFCE_UNAVAILABLE", error:"Falha fiscal segura." }); }
