import { eq, sql } from "drizzle-orm";
import { db, fiscalDocumentsTable, storeFiscalSettingsTable } from "@workspace/db";
import { FocusNfeClient } from "./client";
import { FOCUS_NFCE_ENDPOINTS, normalizeFocusNfceStatus } from "./nfce-contract";
import { getFocusCompanySummary, resolveStoreFocusCredentials } from "./company-service";
import { FocusNfeError } from "./errors";
import { audit, findNfceDocument, reserveHomologationNfce, reserveProductionNfce, toSafeNfceDocument } from "./nfce-repository";
import { NfceServiceError, type FocusNfceResponse } from "./nfce-types";

function normalize(data: FocusNfceResponse){ return normalizeFocusNfceStatus(data as Record<string, unknown>); }
async function assertSetupReady(storeId:number, environment:"homologation"|"production"="homologation"){ const summary=await getFocusCompanySummary(storeId); if(environment === "production" && !summary.readyForProduction) throw new NfceServiceError("FISCAL_PRODUCTION_NOT_READY" as any,"Emissão em produção bloqueada: finalize a configuração fiscal da loja antes de emitir NFC-e real.",409); if(environment === "homologation" && !summary.readyForHomologationTest) throw new NfceServiceError("FISCAL_SETUP_NOT_READY","Configuração fiscal não está pronta para homologação."); }
async function applyResult(storeId:number,userId:number,docId:number,data:FocusNfceResponse, checked=false, environment:"homologation"|"production"="homologation"){ const n=normalize(data); const now=new Date(); const [updated]=await db.transaction(async(tx:any)=>{ const [d]=await tx.update(fiscalDocumentsTable).set({ status:n.status, providerStatus:n.providerStatus, accessKey:n.accessKey, protocol:n.protocol, xmlUrl:n.xmlUrl, danfceUrl:n.danfceUrl, rejectionCode:n.rejectionCode, rejectionMessage:n.rejectionMessage, lastCheckedAt:checked?now:undefined, authorizedAt:n.status==="authorized"?now:undefined }).where(eq(fiscalDocumentsTable.id,docId)).returning(); if(n.status==="authorized" && environment === "homologation"){ await tx.update(storeFiscalSettingsTable).set({ certificateStatus:"valid", setupStatus:"homologation" }).where(eq(storeFiscalSettingsTable.storeId, storeId)); } return [d]; }); if(n.status==="authorized"){ await audit(storeId,userId,`nfce_${environment}_authorized`,docId,{ fiscalDocumentId:docId, status:n.status, accessKey:n.accessKey, protocol:n.protocol }); await audit(storeId,userId,"fiscal_certificate_confirmed_by_authorized_nfce",docId,{ fiscalDocumentId:docId, status:n.status }); if (environment === "homologation") await audit(storeId,userId,"fiscal_homologation_confirmed",docId,{ fiscalDocumentId:docId, status:n.status }); } else if(n.status==="rejected") await audit(storeId,userId,`nfce_${environment}_rejected`,docId,{ fiscalDocumentId:docId, status:n.status, rejectionCode:n.rejectionCode }); else await audit(storeId,userId,`nfce_${environment}_processing`,docId,{ fiscalDocumentId:docId, status:n.status }); return toSafeNfceDocument(updated); }
export class NfceService { constructor(private client = new FocusNfeClient()){}
  private async issue(storeId:number, orderId:number, userId:number, environment:"homologation"|"production"){ await assertSetupReady(storeId, environment); const doc= environment === "production" ? await reserveProductionNfce(storeId,orderId,userId) : await reserveHomologationNfce(storeId,orderId,userId); if(doc.status==="authorized") throw new NfceServiceError("NFCE_ALREADY_AUTHORIZED","NFC-e já autorizada."); if(doc.status==="rejected") throw new NfceServiceError("NFCE_REJECTED","NFC-e rejeitada. Use a atualização de status antes de corrigir em um fluxo futuro."); if(doc.status==="sync_pending") throw new NfceServiceError("FISCAL_DOCUMENT_SYNC_PENDING","Documento fiscal pendente de sincronização com a Focus.",202); if(["submitting","processing"].includes(doc.status)) throw new NfceServiceError("NFCE_PROCESSING","NFC-e em processamento."); await db.update(fiscalDocumentsTable).set({ status:"submitting", attemptCount: sql`${fiscalDocumentsTable.attemptCount} + 1`, lastAttemptAt:new Date() }).where(eq(fiscalDocumentsTable.id,doc.id)); await audit(storeId,userId,`nfce_${environment}_submitted`,doc.id,{ fiscalDocumentId:doc.id, status:"submitting", series:doc.series, number:doc.number, providerReference:doc.providerReference }); const context=await resolveStoreFocusCredentials({ storeId, environment }); try { const result=await this.client.request<FocusNfceResponse>(context,{ method:"POST", path:`${FOCUS_NFCE_ENDPOINTS.createPath}?ref=${encodeURIComponent(doc.providerReference)}`, idempotencyReference:doc.providerReference, body:doc.payloadSnapshot }); return applyResult(storeId,userId,doc.id,result.data,false,environment); } catch(e){ if(e instanceof FocusNfeError && (e.kind==="timeout" || e.kind==="communication" || e.kind==="temporary_unavailable")){ try { const r=await this.client.request<FocusNfceResponse>(context,{ method:"GET", path:FOCUS_NFCE_ENDPOINTS.consultPath(doc.providerReference) }); return applyResult(storeId,userId,doc.id,r.data,true,environment); } catch { await db.update(fiscalDocumentsTable).set({ status:"sync_pending", lastCheckedAt:new Date() }).where(eq(fiscalDocumentsTable.id,doc.id)); await audit(storeId,userId,`nfce_${environment}_sync_pending`,doc.id,{ fiscalDocumentId:doc.id, status:"sync_pending", providerReference:doc.providerReference }); throw new NfceServiceError("FISCAL_DOCUMENT_SYNC_PENDING","Não foi possível confirmar a situação da NFC-e na Focus.",202); } } if(e instanceof FocusNfeError && e.kind==="timeout") throw new NfceServiceError("FOCUS_NFCE_TIMEOUT","Tempo esgotado ao comunicar com a Focus.",504); if(e instanceof FocusNfeError && e.kind==="validation") throw new NfceServiceError("FOCUS_NFCE_VALIDATION_ERROR","Focus rejeitou a validação da NFC-e.",422); throw new NfceServiceError("FOCUS_NFCE_UNAVAILABLE","Focus NFe indisponível.",503); } }
  async issueHomologation(storeId:number, orderId:number, userId:number){ return this.issue(storeId, orderId, userId, "homologation"); }
  async issueProduction(storeId:number, orderId:number, userId:number){ return this.issue(storeId, orderId, userId, "production"); }
  async getLocal(storeId:number,orderId:number, environment:"homologation"|"production"="homologation"){ const d=await findNfceDocument(storeId,orderId,environment); if(!d) throw new NfceServiceError("ORDER_NOT_FOUND","Documento fiscal não encontrado.",404); return toSafeNfceDocument(d); }
  async refresh(storeId:number,orderId:number,userId:number, environment:"homologation"|"production"="homologation"){ await assertSetupReady(storeId, environment); const doc=await findNfceDocument(storeId,orderId,environment); if(!doc) throw new NfceServiceError("ORDER_NOT_FOUND","Documento fiscal não encontrado.",404); const context=await resolveStoreFocusCredentials({ storeId, environment }); try { const r=await this.client.request<FocusNfceResponse>(context,{ method:"GET", path:FOCUS_NFCE_ENDPOINTS.consultPath(doc.providerReference) }); return applyResult(storeId,userId,doc.id,r.data,true,environment); } catch { await db.update(fiscalDocumentsTable).set({ status:"sync_pending", lastCheckedAt:new Date() }).where(eq(fiscalDocumentsTable.id,doc.id)); throw new NfceServiceError("FISCAL_DOCUMENT_SYNC_PENDING","Consulta pendente de sincronização.",202); } }
}
export function sendNfceError(res:any,error:unknown){ if(error instanceof NfceServiceError) return res.status(error.status).json({ code:error.code, error:error.message }); return res.status(500).json({ code:"FOCUS_NFCE_UNAVAILABLE", error:"Falha fiscal segura." }); }
